services:
  - type: web
    name: twilio-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        value: your-telegram-bot-token
      - key: ADMIN_ID
        value: your-admin-id
